#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace BP_DissolvedDeath { class UBP_DissolvedDeath_C; }

namespace BP_DissolvedDeath_0 { class UBP_DissolvedDeath_C; }


namespace Solarland
{
	enum class EActionType : uint8;
	enum class EActionType : uint8;
}
