#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_TextureArrayTest

#include "Basic.hpp"

#include "A_TextureArrayTest_classes.hpp"
#include "A_TextureArrayTest_parameters.hpp"


namespace SDK
{

// Function A_TextureArrayTest.A_TextureArrayTest_C.ExecuteUbergraph_A_TextureArrayTest
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_TextureArrayTest_C::ExecuteUbergraph_A_TextureArrayTest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_TextureArrayTest_C", "ExecuteUbergraph_A_TextureArrayTest");

	Params::A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_TextureArrayTest.A_TextureArrayTest_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_TextureArrayTest_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_TextureArrayTest_C", "ReceiveTick");

	Params::A_TextureArrayTest_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_TextureArrayTest.A_TextureArrayTest_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AA_TextureArrayTest_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_TextureArrayTest_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function A_TextureArrayTest.A_TextureArrayTest_C.TextureArrayTestFunc
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AA_TextureArrayTest_C::TextureArrayTestFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_TextureArrayTest_C", "TextureArrayTestFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

