#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_TextureArrayTest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass A_TextureArrayTest.A_TextureArrayTest_C
// 0x0030 (0x0308 - 0x02D8)
class AA_TextureArrayTest_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneCaptureComponent2D*               SceneCaptureComponent2D;                           // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FString                                 TextureArrayPixel;                                 // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_A_TextureArrayTest(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void TextureArrayTestFunc();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"A_TextureArrayTest_C">();
	}
	static class AA_TextureArrayTest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AA_TextureArrayTest_C>();
	}
};
static_assert(alignof(AA_TextureArrayTest_C) == 0x000008, "Wrong alignment on AA_TextureArrayTest_C");
static_assert(sizeof(AA_TextureArrayTest_C) == 0x000308, "Wrong size on AA_TextureArrayTest_C");
static_assert(offsetof(AA_TextureArrayTest_C, UberGraphFrame) == 0x0002D8, "Member 'AA_TextureArrayTest_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AA_TextureArrayTest_C, SceneCaptureComponent2D) == 0x0002E0, "Member 'AA_TextureArrayTest_C::SceneCaptureComponent2D' has a wrong offset!");
static_assert(offsetof(AA_TextureArrayTest_C, StaticMesh) == 0x0002E8, "Member 'AA_TextureArrayTest_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(AA_TextureArrayTest_C, DefaultSceneRoot) == 0x0002F0, "Member 'AA_TextureArrayTest_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AA_TextureArrayTest_C, TextureArrayPixel) == 0x0002F8, "Member 'AA_TextureArrayTest_C::TextureArrayPixel' has a wrong offset!");

}

