#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_TextureArrayTest

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function A_TextureArrayTest.A_TextureArrayTest_C.ExecuteUbergraph_A_TextureArrayTest
// 0x0008 (0x0008 - 0x0000)
struct A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest) == 0x000004, "Wrong alignment on A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest");
static_assert(sizeof(A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest) == 0x000008, "Wrong size on A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest");
static_assert(offsetof(A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest, EntryPoint) == 0x000000, "Member 'A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest::EntryPoint' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'A_TextureArrayTest_C_ExecuteUbergraph_A_TextureArrayTest::K2Node_Event_DeltaSeconds' has a wrong offset!");

// Function A_TextureArrayTest.A_TextureArrayTest_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct A_TextureArrayTest_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(A_TextureArrayTest_C_ReceiveTick) == 0x000004, "Wrong alignment on A_TextureArrayTest_C_ReceiveTick");
static_assert(sizeof(A_TextureArrayTest_C_ReceiveTick) == 0x000004, "Wrong size on A_TextureArrayTest_C_ReceiveTick");
static_assert(offsetof(A_TextureArrayTest_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'A_TextureArrayTest_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function A_TextureArrayTest.A_TextureArrayTest_C.TextureArrayTestFunc
// 0x00F0 (0x00F0 - 0x0000)
struct A_TextureArrayTest_C_TextureArrayTestFunc final
{
public:
	TSoftObjectPtr<class UMaterial>               Material;                                          // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_SoftObjectReferenceToString_ReturnValue; // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UMaterial*                              K2Node_DynamicCast_AsMaterial;                     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class USolarGameInstanceBase*                 CallFunc_GetSolarGameInstanceBase_ReturnValue;     // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USolarHttpManager*                      CallFunc_GetSolarHttpManager_ReturnValue;          // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_ReadRenderTargetRawPixel_ReturnValue;     // 0x00C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ColorToString_ReturnValue;           // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x00E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(A_TextureArrayTest_C_TextureArrayTestFunc) == 0x000008, "Wrong alignment on A_TextureArrayTest_C_TextureArrayTestFunc");
static_assert(sizeof(A_TextureArrayTest_C_TextureArrayTestFunc) == 0x0000F0, "Wrong size on A_TextureArrayTest_C_TextureArrayTestFunc");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, Material) == 0x000000, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::Material' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue) == 0x000028, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Conv_SoftObjectReferenceToString_ReturnValue) == 0x000038, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Conv_SoftObjectReferenceToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000048, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000050, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, K2Node_DynamicCast_AsMaterial) == 0x000060, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::K2Node_DynamicCast_AsMaterial' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000070, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000080, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_4) == 0x000090, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_5) == 0x0000A0, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_GetSolarGameInstanceBase_ReturnValue) == 0x0000B0, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_GetSolarGameInstanceBase_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_GetSolarHttpManager_ReturnValue) == 0x0000B8, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_GetSolarHttpManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_ReadRenderTargetRawPixel_ReturnValue) == 0x0000C0, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_ReadRenderTargetRawPixel_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Conv_ColorToString_ReturnValue) == 0x0000D0, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Conv_ColorToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(A_TextureArrayTest_C_TextureArrayTestFunc, CallFunc_Concat_StrStr_ReturnValue_6) == 0x0000E0, "Member 'A_TextureArrayTest_C_TextureArrayTestFunc::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");

}

