#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyGameState

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LobbyGameState.BP_LobbyGameState_C
// 0x0008 (0x03D8 - 0x03D0)
class ABP_LobbyGameState_C final : public ASolarGameStateBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LobbyGameState_C">();
	}
	static class ABP_LobbyGameState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LobbyGameState_C>();
	}
};
static_assert(alignof(ABP_LobbyGameState_C) == 0x000008, "Wrong alignment on ABP_LobbyGameState_C");
static_assert(sizeof(ABP_LobbyGameState_C) == 0x0003D8, "Wrong size on ABP_LobbyGameState_C");
static_assert(offsetof(ABP_LobbyGameState_C, DefaultSceneRoot) == 0x0003D0, "Member 'ABP_LobbyGameState_C::DefaultSceneRoot' has a wrong offset!");

}

