#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyMode

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LobbyMode.BP_LobbyMode_C
// 0x0008 (0x0380 - 0x0378)
class ABP_LobbyMode_C final : public AGameModeBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LobbyMode_C">();
	}
	static class ABP_LobbyMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LobbyMode_C>();
	}
};
static_assert(alignof(ABP_LobbyMode_C) == 0x000008, "Wrong alignment on ABP_LobbyMode_C");
static_assert(sizeof(ABP_LobbyMode_C) == 0x000380, "Wrong size on ABP_LobbyMode_C");
static_assert(offsetof(ABP_LobbyMode_C, DefaultSceneRoot) == 0x000378, "Member 'ABP_LobbyMode_C::DefaultSceneRoot' has a wrong offset!");

}

