#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SolarRuntimeAssetsCollection

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SolarRuntimeAssetsCollection.BP_SolarRuntimeAssetsCollection_C
// 0x0000 (0x0038 - 0x0038)
class UBP_SolarRuntimeAssetsCollection_C final : public USolarRuntimeAssetsCollection
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SolarRuntimeAssetsCollection_C">();
	}
	static class UBP_SolarRuntimeAssetsCollection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SolarRuntimeAssetsCollection_C>();
	}
};
static_assert(alignof(UBP_SolarRuntimeAssetsCollection_C) == 0x000008, "Wrong alignment on UBP_SolarRuntimeAssetsCollection_C");
static_assert(sizeof(UBP_SolarRuntimeAssetsCollection_C) == 0x000038, "Wrong size on UBP_SolarRuntimeAssetsCollection_C");

}

