#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Login

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Login.Login_C
// 0x0000 (0x02E0 - 0x02E0)
class ALogin_C final : public ALevelScriptActor
{
public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveBeginPlay();

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Login_C">();
	}
	static class ALogin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALogin_C>();
	}
};
static_assert(alignof(ALogin_C) == 0x000008, "Wrong alignment on ALogin_C");
static_assert(sizeof(ALogin_C) == 0x0002E0, "Wrong size on ALogin_C");

}

