#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Login

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Login.Login_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct Login_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(Login_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on Login_C_ReceiveEndPlay");
static_assert(sizeof(Login_C_ReceiveEndPlay) == 0x000001, "Wrong size on Login_C_ReceiveEndPlay");
static_assert(offsetof(Login_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'Login_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function Login.Login_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct Login_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
static_assert(alignof(Login_C_GetModuleName) == 0x000008, "Wrong alignment on Login_C_GetModuleName");
static_assert(sizeof(Login_C_GetModuleName) == 0x000010, "Wrong size on Login_C_GetModuleName");
static_assert(offsetof(Login_C_GetModuleName, ReturnValue) == 0x000000, "Member 'Login_C_GetModuleName::ReturnValue' has a wrong offset!");

}

