#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Update_Server_Btn

#include "Basic.hpp"

#include "UI_Update_Server_Btn_classes.hpp"
#include "UI_Update_Server_Btn_parameters.hpp"


namespace SDK
{

// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.ExecuteUbergraph_UI_Update_Server_Btn
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Update_Server_Btn_C::ExecuteUbergraph_UI_Update_Server_Btn(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "ExecuteUbergraph_UI_Update_Server_Btn");

	Params::UI_Update_Server_Btn_C_ExecuteUbergraph_UI_Update_Server_Btn Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.ReceivePlatformLayout
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// EUSolarWidgetLayoutType                 InLayoutType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Update_Server_Btn_C::ReceivePlatformLayout(EUSolarWidgetLayoutType InLayoutType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "ReceivePlatformLayout");

	Params::UI_Update_Server_Btn_C_ReceivePlatformLayout Parms{};

	Parms.InLayoutType = InLayoutType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Update_Server_Btn_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "OnMouseLeave");

	Params::UI_Update_Server_Btn_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Update_Server_Btn_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "OnMouseEnter");

	Params::UI_Update_Server_Btn_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Update_Server_Btn_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "PreConstruct");

	Params::UI_Update_Server_Btn_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.Set Is Select
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Update_Server_Btn_C::Set_Is_Select(bool Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "Set Is Select");

	Params::UI_Update_Server_Btn_C_Set_Is_Select Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.SetInternationalServer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInternationalServer_0                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Update_Server_Btn_C::SetInternationalServer(bool IsInternationalServer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "SetInternationalServer");

	Params::UI_Update_Server_Btn_C_SetInternationalServer Parms{};

	Parms.IsInternationalServer_0 = IsInternationalServer_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.SetState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Update_Server_Btn_C::SetState(bool State_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "SetState");

	Params::UI_Update_Server_Btn_C_SetState Parms{};

	Parms.State_0 = State_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Update_Server_Btn.UI_Update_Server_Btn_C.RefreshLatencyTxtColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Update_Server_Btn_C::RefreshLatencyTxtColor(int32 NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Update_Server_Btn_C", "RefreshLatencyTxtColor");

	Params::UI_Update_Server_Btn_C_RefreshLatencyTxtColor Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}

}

