#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Update_UID

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Update_UID.UI_Update_UID_C
// 0x0020 (0x0610 - 0x05F0)
class UUI_Update_UID_C final : public USolarUserWidget
{
public:
	class UButton*                                Btn_Switch;                                        // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Switch;                                    // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_UID;                                           // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_PlayerHead_C*             UI_Component_PlayerHead;                           // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Update_UID_C">();
	}
	static class UUI_Update_UID_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Update_UID_C>();
	}
};
static_assert(alignof(UUI_Update_UID_C) == 0x000008, "Wrong alignment on UUI_Update_UID_C");
static_assert(sizeof(UUI_Update_UID_C) == 0x000610, "Wrong size on UUI_Update_UID_C");
static_assert(offsetof(UUI_Update_UID_C, Btn_Switch) == 0x0005F0, "Member 'UUI_Update_UID_C::Btn_Switch' has a wrong offset!");
static_assert(offsetof(UUI_Update_UID_C, SizeBox_Switch) == 0x0005F8, "Member 'UUI_Update_UID_C::SizeBox_Switch' has a wrong offset!");
static_assert(offsetof(UUI_Update_UID_C, Txt_UID) == 0x000600, "Member 'UUI_Update_UID_C::Txt_UID' has a wrong offset!");
static_assert(offsetof(UUI_Update_UID_C, UI_Component_PlayerHead) == 0x000608, "Member 'UUI_Update_UID_C::UI_Component_PlayerHead' has a wrong offset!");

}

