#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_UpdateLoadingBase

#include "Basic.hpp"

#include "UI_UpdateLoadingBase_classes.hpp"
#include "UI_UpdateLoadingBase_parameters.hpp"


namespace SDK
{

// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.ExecuteUbergraph_UI_UpdateLoadingBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_UpdateLoadingBase_C::ExecuteUbergraph_UI_UpdateLoadingBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_UpdateLoadingBase_C", "ExecuteUbergraph_UI_UpdateLoadingBase");

	Params::UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_UpdateLoadingBase_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_UpdateLoadingBase_C", "Tick");

	Params::UI_UpdateLoadingBase_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_UpdateLoadingBase_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_UpdateLoadingBase_C", "PreConstruct");

	Params::UI_UpdateLoadingBase_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.SetImgBgHidden
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_UpdateLoadingBase_C::SetImgBgHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_UpdateLoadingBase_C", "SetImgBgHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.SetPercentText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UUI_UpdateLoadingBase_C::SetPercentText(const class FText& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_UpdateLoadingBase_C", "SetPercentText");

	Params::UI_UpdateLoadingBase_C_SetPercentText Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}

}

