#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_UpdateLoadingBase

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.ExecuteUbergraph_UI_UpdateLoadingBase
// 0x0044 (0x0044 - 0x0000)
struct UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase) == 0x000004, "Wrong alignment on UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase");
static_assert(sizeof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase) == 0x000044, "Wrong size on UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase");
static_assert(offsetof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase, EntryPoint) == 0x000000, "Member 'UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase, K2Node_Event_MyGeometry) == 0x000004, "Member 'UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase, K2Node_Event_InDeltaTime) == 0x00003C, "Member 'UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase, K2Node_Event_IsDesignTime) == 0x000040, "Member 'UI_UpdateLoadingBase_C_ExecuteUbergraph_UI_UpdateLoadingBase::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.Tick
// 0x003C (0x003C - 0x0000)
struct UI_UpdateLoadingBase_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_UpdateLoadingBase_C_Tick) == 0x000004, "Wrong alignment on UI_UpdateLoadingBase_C_Tick");
static_assert(sizeof(UI_UpdateLoadingBase_C_Tick) == 0x00003C, "Wrong size on UI_UpdateLoadingBase_C_Tick");
static_assert(offsetof(UI_UpdateLoadingBase_C_Tick, MyGeometry) == 0x000000, "Member 'UI_UpdateLoadingBase_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_UpdateLoadingBase_C_Tick, InDeltaTime) == 0x000038, "Member 'UI_UpdateLoadingBase_C_Tick::InDeltaTime' has a wrong offset!");

// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_UpdateLoadingBase_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_UpdateLoadingBase_C_PreConstruct) == 0x000001, "Wrong alignment on UI_UpdateLoadingBase_C_PreConstruct");
static_assert(sizeof(UI_UpdateLoadingBase_C_PreConstruct) == 0x000001, "Wrong size on UI_UpdateLoadingBase_C_PreConstruct");
static_assert(offsetof(UI_UpdateLoadingBase_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_UpdateLoadingBase_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_UpdateLoadingBase.UI_UpdateLoadingBase_C.SetPercentText
// 0x0018 (0x0018 - 0x0000)
struct UI_UpdateLoadingBase_C_SetPercentText final
{
public:
	class FText                                   NewParam;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(UI_UpdateLoadingBase_C_SetPercentText) == 0x000008, "Wrong alignment on UI_UpdateLoadingBase_C_SetPercentText");
static_assert(sizeof(UI_UpdateLoadingBase_C_SetPercentText) == 0x000018, "Wrong size on UI_UpdateLoadingBase_C_SetPercentText");
static_assert(offsetof(UI_UpdateLoadingBase_C_SetPercentText, NewParam) == 0x000000, "Member 'UI_UpdateLoadingBase_C_SetPercentText::NewParam' has a wrong offset!");

}

