#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Update

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Update.UI_Update_C
// 0x0190 (0x0780 - 0x05F0)
class UUI_Update_C final : public UUpdateWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Enter;                                        // 0x05F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    Btn_Account;                                       // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_AgeLimit;                                      // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    Btn_Bind_ActivationCode;                           // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    Btn_Bind_PhoneNumber;                              // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_Fix;                                           // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    btn_link;                                          // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_Mute;                                          // 0x0630(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Update_Server_Btn_C*                Btn_National;                                      // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    btn_new;                                           // 0x0640(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_Normal;                                        // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_Notice;                                        // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Update_Server_Btn_C*                Btn_OutSide;                                       // 0x0658(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Update_Server_Btn_C*                Btn_Server;                                        // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Btn_C*                    Btn_Vistor;                                        // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_1;                                     // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_Server;                                // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_0;                                   // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_1;                                   // 0x0688(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_172;                                         // 0x0690(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Bg;                                            // 0x0698(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Bg_Update;                                     // 0x06A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Logo;                                          // 0x06A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Mask;                                          // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_KeyPrompt_C*                        KeyBack;                                           // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Panel_Load;                                        // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Panel_Server;                                      // 0x06C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_Download;                              // 0x06D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_129;                                      // 0x06D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Fix;                                       // 0x06E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Notice;                                    // 0x06E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Volume;                                    // 0x06F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                StartGame;                                         // 0x06F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        StartGameText;                                     // 0x0700(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTileView*                              TileView_ServerList;                               // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_GameInfo_CN;                                   // 0x0710(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_LatestBuildNumber;                             // 0x0718(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_Progress;                                      // 0x0720(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_SourceBuildNumber;                             // 0x0728(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_Tips_1;                                        // 0x0730(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Hover_Square_0px_C*       UI_Btn_Fix;                                        // 0x0738(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Hover_Square_0px_C*       UI_Btn_Notice;                                     // 0x0740(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Hover_Square_0px_C*       UI_Btn_Volume;                                     // 0x0748(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Update_UID_C*                       UI_Update_UID;                                     // 0x0750(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_UpdateLoadingBase_C*                UpdateLoadingBase;                                 // 0x0758(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        wgs_start;                                         // 0x0760(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Volume;                             // 0x0768(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMediaPlayer*                           ClearMediaPlayer;                                  // 0x0770(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMediaPlayer*                           NoClearMediaPlayer;                                // 0x0778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Update(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void PreConstruct(bool IsDesignTime);
	void FinishLoadLobby(int32 Type);
	void OnVideoReady();
	void RefreshLoadingPoints(int32 Index_0);
	void RefreshLoadingPointsAr(int32 Index_0);
	void TextureArrayTestFunc();
	void OnSolarUIOpened();
	void OnInitialized();
	void Destruct();
	void RequestQuitGame();
	void OnSolarUIClosed();
	void TryConnectGate();
	void ReceiveTick(const struct FGeometry& MyGeometry, float InDeltaTime);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Update_C">();
	}
	static class UUI_Update_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Update_C>();
	}
};
static_assert(alignof(UUI_Update_C) == 0x000008, "Wrong alignment on UUI_Update_C");
static_assert(sizeof(UUI_Update_C) == 0x000780, "Wrong size on UUI_Update_C");
static_assert(offsetof(UUI_Update_C, UberGraphFrame) == 0x0005F0, "Member 'UUI_Update_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Anim_Enter) == 0x0005F8, "Member 'UUI_Update_C::Anim_Enter' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Account) == 0x000600, "Member 'UUI_Update_C::Btn_Account' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_AgeLimit) == 0x000608, "Member 'UUI_Update_C::Btn_AgeLimit' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Bind_ActivationCode) == 0x000610, "Member 'UUI_Update_C::Btn_Bind_ActivationCode' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Bind_PhoneNumber) == 0x000618, "Member 'UUI_Update_C::Btn_Bind_PhoneNumber' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Fix) == 0x000620, "Member 'UUI_Update_C::Btn_Fix' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, btn_link) == 0x000628, "Member 'UUI_Update_C::btn_link' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Mute) == 0x000630, "Member 'UUI_Update_C::Btn_Mute' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_National) == 0x000638, "Member 'UUI_Update_C::Btn_National' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, btn_new) == 0x000640, "Member 'UUI_Update_C::btn_new' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Normal) == 0x000648, "Member 'UUI_Update_C::Btn_Normal' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Notice) == 0x000650, "Member 'UUI_Update_C::Btn_Notice' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_OutSide) == 0x000658, "Member 'UUI_Update_C::Btn_OutSide' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Server) == 0x000660, "Member 'UUI_Update_C::Btn_Server' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Btn_Vistor) == 0x000668, "Member 'UUI_Update_C::Btn_Vistor' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, CanvasPanel_1) == 0x000670, "Member 'UUI_Update_C::CanvasPanel_1' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, CanvasPanel_Server) == 0x000678, "Member 'UUI_Update_C::CanvasPanel_Server' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, HorizontalBox_0) == 0x000680, "Member 'UUI_Update_C::HorizontalBox_0' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, HorizontalBox_1) == 0x000688, "Member 'UUI_Update_C::HorizontalBox_1' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Image_172) == 0x000690, "Member 'UUI_Update_C::Image_172' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Img_Bg) == 0x000698, "Member 'UUI_Update_C::Img_Bg' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Img_Bg_Update) == 0x0006A0, "Member 'UUI_Update_C::Img_Bg_Update' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Img_Logo) == 0x0006A8, "Member 'UUI_Update_C::Img_Logo' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Img_Mask) == 0x0006B0, "Member 'UUI_Update_C::Img_Mask' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, KeyBack) == 0x0006B8, "Member 'UUI_Update_C::KeyBack' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Panel_Load) == 0x0006C0, "Member 'UUI_Update_C::Panel_Load' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Panel_Server) == 0x0006C8, "Member 'UUI_Update_C::Panel_Server' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, ProgressBar_Download) == 0x0006D0, "Member 'UUI_Update_C::ProgressBar_Download' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, SafeZone_129) == 0x0006D8, "Member 'UUI_Update_C::SafeZone_129' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, SizeBox_Fix) == 0x0006E0, "Member 'UUI_Update_C::SizeBox_Fix' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, SizeBox_Notice) == 0x0006E8, "Member 'UUI_Update_C::SizeBox_Notice' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, SizeBox_Volume) == 0x0006F0, "Member 'UUI_Update_C::SizeBox_Volume' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, StartGame) == 0x0006F8, "Member 'UUI_Update_C::StartGame' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, StartGameText) == 0x000700, "Member 'UUI_Update_C::StartGameText' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, TileView_ServerList) == 0x000708, "Member 'UUI_Update_C::TileView_ServerList' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Txt_GameInfo_CN) == 0x000710, "Member 'UUI_Update_C::Txt_GameInfo_CN' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Txt_LatestBuildNumber) == 0x000718, "Member 'UUI_Update_C::Txt_LatestBuildNumber' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Txt_Progress) == 0x000720, "Member 'UUI_Update_C::Txt_Progress' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Txt_SourceBuildNumber) == 0x000728, "Member 'UUI_Update_C::Txt_SourceBuildNumber' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, Txt_Tips_1) == 0x000730, "Member 'UUI_Update_C::Txt_Tips_1' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, UI_Btn_Fix) == 0x000738, "Member 'UUI_Update_C::UI_Btn_Fix' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, UI_Btn_Notice) == 0x000740, "Member 'UUI_Update_C::UI_Btn_Notice' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, UI_Btn_Volume) == 0x000748, "Member 'UUI_Update_C::UI_Btn_Volume' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, UI_Update_UID) == 0x000750, "Member 'UUI_Update_C::UI_Update_UID' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, UpdateLoadingBase) == 0x000758, "Member 'UUI_Update_C::UpdateLoadingBase' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, wgs_start) == 0x000760, "Member 'UUI_Update_C::wgs_start' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, WidgetSwitcher_Volume) == 0x000768, "Member 'UUI_Update_C::WidgetSwitcher_Volume' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, ClearMediaPlayer) == 0x000770, "Member 'UUI_Update_C::ClearMediaPlayer' has a wrong offset!");
static_assert(offsetof(UUI_Update_C, NoClearMediaPlayer) == 0x000778, "Member 'UUI_Update_C::NoClearMediaPlayer' has a wrong offset!");

}

