#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Update_Server_Btn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SolarUI_structs.hpp"
#include "E_Lobby_Latency_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Solarland_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Update_Server_Btn.UI_Update_Server_Btn_C
// 0x0078 (0x0668 - 0x05F0)
class UUI_Update_Server_Btn_C final : public USolarUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Btn_Server;                                        // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Arrow;                                         // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Bg_2;                                          // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Serverc;                                   // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_ms;                                            // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_Server;                                        // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Component_Hover_Square_0px_C*       UI_Component_Hover_Square_0px;                     // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0630(0x0018)(Edit, BlueprintVisible)
	bool                                          IsLoc;                                             // 0x0648(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_649[0x3];                                      // 0x0649(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LocID;                                             // 0x064C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInternationalServer;                             // 0x0650(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          State;                                             // 0x0651(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_652[0x2];                                      // 0x0652(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              MobileSize;                                        // 0x0654(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              PCSize;                                            // 0x065C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Lobby_Latency                               LobbyLatency;                                      // 0x0664(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Update_Server_Btn(int32 EntryPoint);
	void ReceivePlatformLayout(EUSolarWidgetLayoutType InLayoutType);
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void PreConstruct(bool IsDesignTime);
	void Set_Is_Select(bool Index_0);
	void SetInternationalServer(bool IsInternationalServer_0);
	void SetState(bool State_0);
	void RefreshLatencyTxtColor(int32 NewParam);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Update_Server_Btn_C">();
	}
	static class UUI_Update_Server_Btn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Update_Server_Btn_C>();
	}
};
static_assert(alignof(UUI_Update_Server_Btn_C) == 0x000008, "Wrong alignment on UUI_Update_Server_Btn_C");
static_assert(sizeof(UUI_Update_Server_Btn_C) == 0x000668, "Wrong size on UUI_Update_Server_Btn_C");
static_assert(offsetof(UUI_Update_Server_Btn_C, UberGraphFrame) == 0x0005F0, "Member 'UUI_Update_Server_Btn_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Btn_Server) == 0x0005F8, "Member 'UUI_Update_Server_Btn_C::Btn_Server' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Img_Arrow) == 0x000600, "Member 'UUI_Update_Server_Btn_C::Img_Arrow' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Img_Bg_2) == 0x000608, "Member 'UUI_Update_Server_Btn_C::Img_Bg_2' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, SizeBox_Serverc) == 0x000610, "Member 'UUI_Update_Server_Btn_C::SizeBox_Serverc' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Txt_ms) == 0x000618, "Member 'UUI_Update_Server_Btn_C::Txt_ms' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Txt_Server) == 0x000620, "Member 'UUI_Update_Server_Btn_C::Txt_Server' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, UI_Component_Hover_Square_0px) == 0x000628, "Member 'UUI_Update_Server_Btn_C::UI_Component_Hover_Square_0px' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, Text) == 0x000630, "Member 'UUI_Update_Server_Btn_C::Text' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, IsLoc) == 0x000648, "Member 'UUI_Update_Server_Btn_C::IsLoc' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, LocID) == 0x00064C, "Member 'UUI_Update_Server_Btn_C::LocID' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, IsInternationalServer) == 0x000650, "Member 'UUI_Update_Server_Btn_C::IsInternationalServer' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, State) == 0x000651, "Member 'UUI_Update_Server_Btn_C::State' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, MobileSize) == 0x000654, "Member 'UUI_Update_Server_Btn_C::MobileSize' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, PCSize) == 0x00065C, "Member 'UUI_Update_Server_Btn_C::PCSize' has a wrong offset!");
static_assert(offsetof(UUI_Update_Server_Btn_C, LobbyLatency) == 0x000664, "Member 'UUI_Update_Server_Btn_C::LobbyLatency' has a wrong offset!");

}

