#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_UpdateLoadingBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UI_LoadingBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_UpdateLoadingBase.UI_UpdateLoadingBase_C
// 0x0010 (0x0738 - 0x0728)
class UUI_UpdateLoadingBase_C final : public UUI_LoadingBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0728(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USolarTextBlock*                        Txt_Tips_Title;                                    // 0x0730(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_UpdateLoadingBase(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void PreConstruct(bool IsDesignTime);
	void SetImgBgHidden();
	void SetPercentText(const class FText& NewParam);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_UpdateLoadingBase_C">();
	}
	static class UUI_UpdateLoadingBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_UpdateLoadingBase_C>();
	}
};
static_assert(alignof(UUI_UpdateLoadingBase_C) == 0x000008, "Wrong alignment on UUI_UpdateLoadingBase_C");
static_assert(sizeof(UUI_UpdateLoadingBase_C) == 0x000738, "Wrong size on UUI_UpdateLoadingBase_C");
static_assert(offsetof(UUI_UpdateLoadingBase_C, UberGraphFrame) == 0x000728, "Member 'UUI_UpdateLoadingBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_UpdateLoadingBase_C, Txt_Tips_Title) == 0x000730, "Member 'UUI_UpdateLoadingBase_C::Txt_Tips_Title' has a wrong offset!");

}

