#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIServerList_Item

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIServerList_Item.UIServerList_Item_C
// 0x0020 (0x0610 - 0x05F0)
class UUIServerList_Item_C final : public USolarUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Btn_Selected;                                      // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Selected;                                      // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_ServerName;                                    // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UIServerList_Item(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnEntryReleased();
	bool BP_IsNotSelectableOrNavigable();

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIServerList_Item_C">();
	}
	static class UUIServerList_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIServerList_Item_C>();
	}
};
static_assert(alignof(UUIServerList_Item_C) == 0x000008, "Wrong alignment on UUIServerList_Item_C");
static_assert(sizeof(UUIServerList_Item_C) == 0x000610, "Wrong size on UUIServerList_Item_C");
static_assert(offsetof(UUIServerList_Item_C, UberGraphFrame) == 0x0005F0, "Member 'UUIServerList_Item_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUIServerList_Item_C, Btn_Selected) == 0x0005F8, "Member 'UUIServerList_Item_C::Btn_Selected' has a wrong offset!");
static_assert(offsetof(UUIServerList_Item_C, Img_Selected) == 0x000600, "Member 'UUIServerList_Item_C::Img_Selected' has a wrong offset!");
static_assert(offsetof(UUIServerList_Item_C, Txt_ServerName) == 0x000608, "Member 'UUIServerList_Item_C::Txt_ServerName' has a wrong offset!");

}

